apiVersion: apps/v1
kind: Deployment

metadata:
  name: securebank

spec:
  replicas: 2

  selector:
    matchLabels:
      app: securebank

  template:
    metadata:
      labels:
        app: securebank

    spec:
      containers:
      - name: securebank
        image: devopsbyrushi/securebank:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
